### ISSUE TITLE
New build for F24

### ISSUE THREAD

**Issue by shaynehardesty** [carlwgeorge/nova-agent-rpm#16]
Hey Carl, when you have a few mins can you run a new build for Fedora 24?  If the date doesn't slip again it should release on 6/21.  If you need it, here's a build of Fedora 24 Beta 2 you can use for testing: 743f98f4-1648-41fb-8936-78d9210b54ad.  I was able to use the F23 version of the agent there, so I doubt any changes are needed.

**Comment by carlwgeorge** [comment]
I built a new RPM against an F24 chroot and attached it to the release.

https://github.com/carlwgeorge/nova-agent-rpm/releases/download/1.39.1-2/nova-agent-1.39.1-2.fc24.x86_64.rpm

Since we are dealing with a precompiled binary I don't anticipate any problems (hence why the F23 RPM worked fine).
